// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCes4sFDX6uidGoCKdprU0EA83RZRw7X3k',
    appId: '1:235687948971:web:779576d1014052303fbdee',
    messagingSenderId: '235687948971',
    projectId: 'authemail-60124',
    authDomain: 'authemail-60124.firebaseapp.com',
    storageBucket: 'authemail-60124.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCz-j9CVCJWuGUliCKF58rQVqdDSmxtGCM',
    appId: '1:235687948971:android:7f6000d50865b7e43fbdee',
    messagingSenderId: '235687948971',
    projectId: 'authemail-60124',
    storageBucket: 'authemail-60124.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBQOLQ5GRrIwDtJdTTP74xoxyApauN_yhw',
    appId: '1:235687948971:ios:2ac9970d0dc1c25b3fbdee',
    messagingSenderId: '235687948971',
    projectId: 'authemail-60124',
    storageBucket: 'authemail-60124.appspot.com',
    iosBundleId: 'com.email.emaillogin',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBQOLQ5GRrIwDtJdTTP74xoxyApauN_yhw',
    appId: '1:235687948971:ios:2ac9970d0dc1c25b3fbdee',
    messagingSenderId: '235687948971',
    projectId: 'authemail-60124',
    storageBucket: 'authemail-60124.appspot.com',
    iosBundleId: 'com.email.emaillogin',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCes4sFDX6uidGoCKdprU0EA83RZRw7X3k',
    appId: '1:235687948971:web:1d2001ce390639c83fbdee',
    messagingSenderId: '235687948971',
    projectId: 'authemail-60124',
    authDomain: 'authemail-60124.firebaseapp.com',
    storageBucket: 'authemail-60124.appspot.com',
  );
}
